include:
    - DataStructure:
        - Treap:
            - DataStructure/Treap.cpp
        - Dynamic Segment Tree:
            - DataStructure/DynamicSegmentTree.cpp
        - Pbds Gp Hash Table:
            - DataStructure/PbdsGpHashTable.cpp
        - Pbds Rope:
            - DataStructure/PbdsRope.cpp
        - Pbds Tree:
            - DataStructure/PbdsTree.cpp
        - Pbds Priority Queue:
            - DataStructure/PbdsPriorityQueue.cpp
        - 2DBIT:
            - DataStructure/2DBIT.cpp
        - Persistent Segment Tree:
            - DataStructure/PersistentSegmentTree.cpp
    - Math:
        - FFT:
            - Math/fft.cpp
        - NTT:
            - Math/ntt.cpp
        - FWT:
            - Math/Fwt.cpp
        - Gaussian-Jordan:
            - Math/gaussian.cpp
        - Mu:
            - Math/Mu.cpp
        - Lucas:
            - Math/Lucas.cpp
        - Inv:
            - Math/Inv.cpp
        - CRT:
            - Math/CRT.cpp
        - Generator:
            - Math/Generator.cpp
        - Count Primes:
            - Math/CountPrimes.cpp
        - Pollard Rho:
            - Math/PollardRho.cpp
        - Formula:
            - Math/Formula.tex
        - Matrix:
            - Math/Matrix.cpp
        - Miller Rabin:
            - Math/MillerRabin.cpp
        - Xor Basis:
            - Math/XorBasis.cpp
    - String:
        - KMP:
            - String/KMP.cpp
        - Longest Palindrome:
            - String/LongestPalindrome.cpp
        - Z:
            - String/Z.cpp
        - Booth:
            - String/Booth.cpp
    - Graph:
        - one-out-degree (CSES Planets Cycles):
            - Graph/one-degree-cycle.cpp
        - Dijkstra:
            - Graph/Dijkstra.cpp
        - MaximumFlow:
            - Graph/MaximumFlow.cpp
        - Dinic:
            - Graph/Dinic.cpp
        - SCC:
            - Graph/SCC.cpp
        - VBCC:
            - Graph/VBCC.cpp
        - 2-SAT(CSES Giant Pizza):
            - Graph/2-SAT.cpp
    - DP:
        - Li-Chao Segment Tree:
            - DP/Li-Chao_SegmentTree.cpp
        - CHO:
            - DP/CHO.cpp
        - SOSDP:
            - DP/SOSDP.cpp
    - Geometry:
        - Intersect:
            - Geometry/Intersect.cpp
        - Inside:
            - Geometry/inside.cpp
        - Minimum Euclidean Distance:
            - Geometry/MinimumEuclideanDistance.cpp
        - Convex Hull:
            - Geometry/ConvexHull.cpp
        - 164253 Version:
            - Geometry/164253Version.cpp
    - Tree:
        - Heavy Light Decomposition (modify and query on path):
            - tree/heavy-light-decomposition.cpp
        - LCA:
            - tree/lca.cpp
    - Misc:
        - Tri Search:
            - misc/tri_search.cpp
        - Big Number:
            - misc/BigNum(luoguP1005).cpp
        - 對拍:
            - misc/對拍.md