include:
  - Misc:
    - Contest:
      - Makefile:
        - misc/Makefile
      - Default Code:
        - misc/default-code.hpp
    - 'How Did We Get Here?':
      - Macros:
        - misc/speed/macros.tex
        - misc/speed/macros.hpp
      - constexpr:
        - misc/speed/constexpr.tex
        - misc/speed/constexpr.hpp
      - Bump Allocator:
        - misc/speed/bump-allocator.hpp
    - Tools:
      - Floating Point Binary Search:
        - misc/float-binary-search.hpp
      - SplitMix64:
        - misc/splitmix64.hpp
      - '<random>':
        - misc/random.hpp
    - Algorithms:
      - Bit Hacks:
        - misc/bit-hacks.hpp
      - Aliens Trick:
        - misc/aliens.hpp
      - Hilbert Curve:
        - misc/hilbert.hpp
  - Math:
    - Number Theory:
      - Mod Struct:
        - math/number-theory/modular.tex
        - math/number-theory/modular.hpp
      - Miller-Rabin:
        - math/number-theory/miller-rabin.hpp
    - Combinatorics:
      - Matroid Intersection:
        - math/combinatorics/matroid.tex
        - math/combinatorics/matroid.hpp
dependencies:
  show: true
  ignore_cycles: false
