include:
  - Misc:
    - Contest:
      - Makefile:
        - misc/Makefile
    - 'How Did We Get Here?':
      - Macros:
        - misc/speed/macros.tex
        - misc/speed/macros.hpp
      - constexpr:
        - misc/speed/constexpr.tex
        - misc/speed/constexpr.hpp
      - Bump Allocator:
        - misc/speed/bump-allocator.hpp
    - Tools:
      - Floating Point Binary Search:
        - misc/float-binary-search.hpp
      - SplitMix64:
        - misc/splitmix64.hpp
      - '<random>':
        - misc/random.hpp
    - Algorithms:
      - Bit Hacks:
        - misc/bit-hacks.hpp
      - Aliens Trick:
        - misc/aliens.hpp
      - Hilbert Curve:
        - misc/hilbert.hpp
  - Data Structures:
    - GNU PBDS:
      - ds/pbds.hpp
    - Segment Tree (ZKW):
      - ds/segtree.hpp
    - Wavelet Matrix:
      - ds/wavelet-matrix.hpp
  - Math:
    - Number Theory:
      - Mod Struct:
        - math/number-theory/modular.tex
        - math/number-theory/modular.hpp
      - Miller-Rabin:
        - math/number-theory/miller-rabin.hpp
      - Extended GCD:
        - math/number-theory/extgcd.hpp
      - Chinese Remainder Theorem:
        - math/number-theory/crt.hpp
    - Combinatorics:
      - Matroid Intersection:
        - math/combinatorics/matroid.tex
        - math/combinatorics/matroid.hpp
  - Geometry:
    - Point:
      - geometry/point.hpp
      - Quarternion:
        - geometry/quaternion.hpp

dependencies:
  show: true
  ignore_cycles: false
